sudo: required
services:
    - docker
    
before_install:
    - docker build -t knottthomas/multi-docker-v2 -f ./client/Dockerfile.dev ./client
    
script:
    - docker run knottthomas/multi-docker-v2 npm test -- --coverage
    
after_success:
    - docker build -t knottthomas/multi-client ./client
    - docker build -t knottthomas/multi-nginx ./nginx
    - docker build -t knottthomas/multi-server ./server
    - docker build -t knottthomas/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push knottthomas/multi-client
    - docker push knottthomas/multi-nginx
    - docker push knottthomas/multi-server
    - docker push knottthomas/multi-worker
    